title: 0-Content
tagline: "There is not what is and what should be. There is only what happens and what we do."
tags: realpolitik, sausage making, politics, blog, non-partisan


author: PathologicalHandwaving
